#!/bin/bash


if [ -z "$1" ]; then
    echo "enter a .cpp file plz"
    exit 1
fi


output=$(basename "$1" .cpp)


g++ -o output "$1" 


if [ $? -eq 0 ]; then
    ./output
else
    echo "compilation error"
fi
